name:                xmonad-decoration-ex
version:             0.1.0.0
synopsis: Extended decorations support for XMonad
homepage:            https://github.com/portnov/xmonad-decoration-ex#readme
license:             BSD-3-Clause
author:              Ilya Portnov
maintainer:          portnov84@rambler.ru
copyright:           2023 Ilya Portnov
category:            Desktop
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5
  - xmonad >= 0.17
  - xmonad-contrib >= 0.17
  - data-default
  - containers >= 0.6

ghc-options:
  - -Wunused-imports
  - -Wall
  - -Wwarn=deprecations
  - -Wwarn=dodgy-imports

library:
  source-dirs:      src
